server:
  port: 8080
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root