spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: article
        uri: lb://blog-article
        predicates:
          - Path=/article/**
#        filters:
#          - StripPrefix=1
      - id: blog
        uri: lb://blog-admin
        predicates:
          - Path=/admin/**
#        filters:
#          - StripPrefix=1
      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
          - Path=/baidu/**
        filters:
          - StripPrefix=1
  application:
    name: blog-gateway
  devtools:
    livereload:
      port: 35732
server:
  port: 8000
feign:
  hystrix:
    enabled: true